pr:
  branches:
    include:
      - develop

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Lint
    displayName: Lint Code
    jobs:
      - job: Lint
        displayName: Run ESLint, StyleLint and Prettier
        pool:
          name: "default"
          vmImage: "MacBook M1 Khavol"
        steps:
          - script: |
              yarn install
              yarn lint
              yarn stylelint || exit 1
              yarn prettier:check
            displayName: Lint Code with ESLint and Prettier

  - stage: Build
    displayName: Build Image
    dependsOn: Lint
    jobs:
      - job: Build
        displayName: Build Docker Image
        pool:
          name: "default"
          vmImage: "MacBook M1 Khavol"
        steps:
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                $(tag)
